"""init_db

Revision ID: 22d3a177e35
Revises: None
Create Date: 2015-10-20 20:41:13.385609

"""

# revision identifiers, used by Alembic.
revision = '22d3a177e35'
down_revision = None
import os, sys

from alembic import op
import sqlalchemy as sa

mydir = os.path.dirname(__file__) or '.' 
full  = os.path.abspath(mydir)
model_path = '{0}/../../'.format(full)
sys.path.append(model_path)
import server.models.models 


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('expire_on', sa.DateTime(), nullable=False),
    sa.Column('command_id', sa.Unicode(length=36), nullable=True),
    sa.Column('command_type', sa.Unicode(length=1024), nullable=True),
    sa.Column('command_date', sa.UnicodeText(), nullable=True),
    sa.Column('identity', sa.Unicode(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id')
    )
    op.create_table('local_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('email', sa.Unicode(length=1024), nullable=True),
    sa.Column('country', sa.Unicode(length=1024), nullable=True),
    sa.Column('research_center', sa.Unicode(length=1024), nullable=True),
    sa.Column('occupation', sa.Unicode(length=1024), nullable=True),
    sa.Column('password', sa.Unicode(length=60), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('registeredtool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Unicode(length=1024), nullable=True),
    sa.Column('options', server.models.models.JSONEncodedDict(), nullable=True),
    sa.Column('help', sa.UnicodeText(), nullable=True),
    sa.Column('section', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tree',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('rel_path', sa.Unicode(length=1024), nullable=True),
    sa.Column('parent', sa.Unicode(length=1024), nullable=True),
    sa.Column('id', sa.Unicode(length=1024), nullable=False),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('text', sa.Unicode(length=1024), nullable=True),
    sa.Column('type', sa.Unicode(length=1024), nullable=True),
    sa.Column('icon', sa.Unicode(length=1024), nullable=True),
    sa.Column('state', sa.Unicode(length=1024), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('email', sa.Unicode(length=1024), nullable=True),
    sa.Column('first_name', sa.Unicode(length=1024), nullable=True),
    sa.Column('last_name', sa.Unicode(length=1024), nullable=True),
    sa.Column('password', sa.Unicode(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.Unicode(length=1024), nullable=True),
    sa.Column('serverpath', sa.Unicode(length=1024), nullable=True),
    sa.Column('localpath', sa.Unicode(length=1024), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('text', sa.Unicode(length=1024), nullable=True),
    sa.Column('type', sa.Unicode(length=1024), nullable=True),
    sa.Column('children', sa.Unicode(length=1024), nullable=True),
    sa.Column('icon', sa.Unicode(length=1024), nullable=True),
    sa.Column('user_id', sa.Unicode(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('args', sa.Unicode(length=1024), nullable=True),
    sa.Column('input_path', sa.Unicode(length=1024), nullable=True),
    sa.Column('output_path', sa.Unicode(length=1024), nullable=True),
    sa.Column('name', sa.Unicode(length=1024), nullable=True),
    sa.Column('file_id', sa.Unicode(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['name'], ['registeredtool.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('input_path'),
    sa.UniqueConstraint('output_path')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    op.drop_table('file')
    op.drop_table('user')
    op.drop_table('tree')
    op.drop_table('registeredtool')
    op.drop_table('local_user')
    op.drop_table('command')
    ### end Alembic commands ###
