#!C:\Users\Charles\Documents\poly\A2015\spinalcordtoolbox_web-master\client\ENV\Scripts\python.exe
# EASY-INSTALL-SCRIPT: 'sympy==0.7.6.1','isympy'
__requires__ = 'sympy==0.7.6.1'
__import__('pkg_resources').run_script('sympy==0.7.6.1', 'isympy')
